name = "bireco-backend"
main = "build/worker/shim.mjs"
compatibility_date = "2025-09-09"

[env.development]
name = "bireco-backend-dev"

[env.development.vars]
ALLOWED_ORIGIN = "http://localhost:5173"
JWT_SECRET = "1RTcrEpL0OEMMNDor9fa3HrJ9aRyk3IgRPgDmeHpUXI6X7dzf0OHWC2PhJOkrq5o"


[[env.development.d1_databases]]
binding = "DB"
database_name = "bireco"
database_id = "2bdfb5a0-3117-4547-8455-5b99e8312492"
migrations_dir = "migrations"

[env.production]
name = "bireco-backend"

[env.production.vars]
ALLOWED_ORIGIN = "https://bireco.noisaria.com"
JWT_SECRET = "1RTcrEpL0OEMMNDor9fa3HrJ9aRyk3IgRPgDmeHpUXI6X7dzf0OHWC2PhJOkrq5o"


[[env.production.d1_databases]]
binding = "DB"
database_name = "bireco"
database_id = "2bdfb5a0-3117-4547-8455-5b99e8312492"
migrations_dir = "migrations"

[[d1_databases]]
binding = "DB"
database_name = "bireco"
database_id = "2bdfb5a0-3117-4547-8455-5b99e8312492"
migrations_dir = "migrations"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[routes]]
pattern = "api.bireco.noisaria.com"
custom_domain = true

[observability]
enabled = true

[observability.logs]
invocation_logs = true
head_sampling_rate = 1
