name = "bireco-backend"
main = "build/worker/shim.mjs"
compatibility_date = "2024-09-01"

[env.development]
name = "bireco-backend-dev"

[env.production]
name = "bireco-backend"

[[d1_databases]]
binding = "DB"
database_name = "bireco"
database_id = "61c194c3-a9bf-41c9-ad42-8962a133f11d"
migrations_dir = "migrations"

[vars]
JWT_SECRET = "1RTcrEpL0OEMMNDor9fa3HrJ9aRyk3IgRPgDmeHpUXI6X7dzf0OHWC2PhJOkrq5o"

[build]
command = "cargo install --path ../../worker-build && worker-build --release"